name: Backend Test

on:
  push:
  workflow_dispatch:

jobs:
  misc:
    runs-on: ubuntu-latest
    env:
      CMAKE_DUMMY_WEBUI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
      - run: python -m pip install -r rst/requirements.txt

      - name: Install tarantool
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=1.10 bash

      - name: Install ldoc
        run: >
          tarantoolctl rocks install --server=http://rocks.moonscript.org
          https://raw.githubusercontent.com/tarantool/ldoc/tarantool/ldoc-scm-2.rockspec

      - name: Build cartridge
        env:
          CMAKE_LDOC_FIND_REQUIRED: 'YES'
          CMAKE_SPHINX_FIND_REQUIRED: 'YES'
        run: |
          tarantoolctl rocks make

      - name: Lint
        run: |
          tarantoolctl rocks install luacheck
          .rocks/bin/luacheck .

      - name: Check schema
        run: |
          npm install graphql-cli@3.0.14
          ./fetch-schema.sh

  luatest:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        tarantool: ['1.10']
        include:
        - runs-on: macos-latest
          tarantool: null # we don't choose version in brew
    runs-on: ${{ matrix.runs-on }}
    env:
      CMAKE_DUMMY_WEBUI: true
    steps:
      - uses: actions/checkout@v2

      - name: Install tarantool (apt)
        if: runner.os == 'Linux'
        run: >
          curl -L https://tarantool.io/installer.sh |
          sudo VER=${{ matrix.tarantool }} bash

      - name: Install tarantool (brew)
        if: runner.os == 'macOS'
        run: brew install tarantool

      - name: Install luatest
        run: tarantoolctl rocks install luatest 0.5.2

      - name: Install etcd
        uses: ./.github/actions/setup-etcd
        if: runner.os == 'Linux'
        with:
          etcd-version: v2.3.8
          install-prefix: etcd-v2.3.8

      - name: Cache rocks
        uses: actions/cache@v2
        with:
          path: .rocks/
          key: backend-build-${{ runner.os }}-${{ hashFiles('*.rockspec') }}
          restore-keys: |
            backend-build-${{ runner.os }}-

      - name: Build cartridge
        run: tarantoolctl rocks make

      - name: Run tests
        env:
          CARTRIDGE_OLDER_PATH: cartridge-1.2.0
        run: |
          mkdir -p $CARTRIDGE_OLDER_PATH
          pushd $CARTRIDGE_OLDER_PATH
          # Prerequisite for compatibility.cartridge_upgrade_test
          tarantoolctl rocks install cartridge 1.2.0-1
          popd

          ETCD_PATH=$(which etcd || true)
          if [ -n "$ETCD_PATH" ]; then
            export ETCD_PATH
          fi

          sudo ulimit -n 24576 || true
          .rocks/bin/luatest -v

      - name: Cleanup cached paths
        run: tarantoolctl rocks remove cartridge
