name: Nightly Test

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  # Skip building frontend in tarantoolctl rocks make
  CMAKE_DUMMY_WEBUI: true
  # Prerequisite for some etcd-related tests
  ETCD_PATH: etcd-v2.3.8/etcd

jobs:
  run-tests:
    strategy:
      fail-fast: false
      # matrix:
      #   tarantool: ['1.10', '2.7', '2.8', '2.9']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # - uses: tarantool/setup-tarantool@v1
      #   with:
      #     tarantool-version: '${{ matrix.tarantool }}'
      #     nightly-build: true

      - name: Install latest pre-release Tarantool 2.x
        run: |
          curl -L https://tarantool.io/pre-release/2/installer.sh | bash
          sudo apt-get -y install tarantool

      # Setup etcd
      - name: Install etcd
        uses: ./.github/actions/setup-etcd
        if: runner.os == 'Linux'
        with:
          etcd-version: v2.3.8
          install-prefix: etcd-v2.3.8

      # Setup luatest
      - name: Cache rocks
        uses: actions/cache@v2
        id: cache-rocks
        with:
          path: .rocks/
          key: nightly-rocks-${{ hashFiles('*.rockspec') }}-03
      -
        run: tarantoolctl rocks install luatest 0.5.6
        if: steps.cache-rocks.outputs.cache-hit != 'true'

      - run: tarantoolctl rocks make
      - run: .rocks/bin/luatest -v

      # Cleanup cached paths
      - run: tarantoolctl rocks remove cartridge
